/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'title' : string,
  'content' : string,
  'isbn' : bigint,
  'author' : string,
}
export interface PhonebookEntry { 'name' : string, 'phone' : string }
export interface _SERVICE {
  'addBook' : ActorMethod<[bigint, string, string, string], undefined>,
  'addOrUpdatePhonebookEntry' : ActorMethod<[PhonebookEntry], bigint>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getBook' : ActorMethod<[bigint], [] | [Book]>,
  'getPhonebookEntries' : ActorMethod<[string, string], Array<PhonebookEntry>>,
  'getPhonebookEntry' : ActorMethod<[bigint], [] | [PhonebookEntry]>,
  'searchBooksByTitle' : ActorMethod<[string], Array<Book>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];