/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PhonebookEntry = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Book = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isbn' : IDL.Nat,
  'author' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBook' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addOrUpdatePhonebookEntry' : IDL.Func([PhonebookEntry], [IDL.Nat], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getBook' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
  'getPhonebookEntries' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(PhonebookEntry)],
      ['query'],
    ),
  'getPhonebookEntry' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PhonebookEntry)],
      ['query'],
    ),
  'searchBooksByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PhonebookEntry = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const Book = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isbn' : IDL.Nat,
    'author' : IDL.Text,
  });
  
  return IDL.Service({
    'addBook' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addOrUpdatePhonebookEntry' : IDL.Func([PhonebookEntry], [IDL.Nat], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getBook' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
    'getPhonebookEntries' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(PhonebookEntry)],
        ['query'],
      ),
    'getPhonebookEntry' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PhonebookEntry)],
        ['query'],
      ),
    'searchBooksByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };